<a href="https://colab.research.google.com/github/Aishaabidhussian-byte/Numpy_assignment/blob/main/Numpy_Task_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [ ]:
#Task 1
marks = np.array ([10, 20, 30, 40, 50])
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))


150
30.0
50
10


In [ ]:
#Task 2
num = np.array([45, 80, 30, 90, 55, 20])
print(num[num >= 50])

[80 90 55]


In [ ]:
#Task 3
num2 = np.array([1, 2, 3, 4, 5, 6])
new_num = num2.reshape(2, 3)
print(new_num)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Task 4
num = np.random.randint(40,100,10)
print(num)
print(np.max(num))
print(np.min(num))
print(np.mean(num))

[87 95 44 84 43 86 55 50 72 55]
95
43
67.1


In [ ]:
#Task 5
marks = np.array([35, 67, 89, 45, 90, 22, 70, 58])
passed = marks[marks >=50]
print(passed)
print(len(passed))
fail = marks[marks <=50]
print(fail)
print(len(fail))


[67 89 90 70 58]
5
[35 45 22]
3
